blog/urls.py
from django.urls import path, include,register_converter
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.shortcuts import redirect
from . import views, converters
from django.conf import settings
from django.conf.urls.static import static

register_converter(converters.IntListConverter, 'intlist')

urlpatterns = [
    path('start/start/', lambda req: redirect('/start/')),
    path("", lambda req: redirect("/start/")),
    path("start/", views.start_page, name="start_page"),
    path("post_list/<int:isTextPost>/", views.post_list, name="post_list"),
    path("post/<int:pk>/", views.post_detail, name="post_detail"),
    path('post/new/<int:isTextPost>/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/delete/', views.post_delete, name="post_delete"),
    path("tag/new/", views.tag_new, name="tag_new"),
    path("tag/query/<int:pk>/<int:isTextPost>/", views.tag_post_list, name="tag_post_list"),
    #path("tag/<intlist:pk_list>/", views.tag_list_post_list, name="tag_list_post_list"),
    path("tag/<int:pk>/edit/", views.tag_edit, name="tag_edit"),
    path("tag/<int:pk>/delete/", views.tag_delete, name="tag_delete"),
    path('accounts/login/', auth_views.LoginView.as_view(), name="login"),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),

]   
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls"))
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone, safestring



# no need for this anymore
class Language(models.Model):
    name = models.CharField(max_length = 20)

    def __str__(self):
        return self.name

class Tag(models.Model):
    # languages are also tags now
    STYLE_CHOICES=(
        ("lb","lightblue"),
        ("pb","pastelblue"),
        ("pp","pastelpurple"),
        ("sg", "seagreen"),
        ("ds", "dark sky"),
        ("nb", "navy blue"),
        ("lg", "light grey"),
        ("dd", "delve deeper special"),
        ("sv", "silver"),
        ("gd", "gold"),
    )
    TYPE_CHOICES=(
        ("l", "language tag"),
        ("o", "other"),
    )
    name = models.CharField(max_length=200)
    style = models.CharField(max_length=2, choices=STYLE_CHOICES, default="pb")
    type = models.CharField(max_length=1, choices = TYPE_CHOICES, default="o")

    def __str__(self):
        return self.name

eng = Tag(name="English",style="pp", type="l")

class Post(models.Model):
    TITLE_ALIGN_CHOICES = (
        ("c", "align-center"),
        ("t", "algin-top"),
        ("b", "align-bottom"),
    )

    TITLE_COLOR_CHOICES = (
        ("wh", "white"),
        ("lb","lightblue"),
        ("pb","pastelblue"),
        ("pp","pastelpurple"),
        ("pr","purple"),
        ("sg", "seagreen"),
        ("bl", "inkblack"),
    )

    TITLE_BACKGROUND_CHOICES = (
        ("no", "none"),
        ("gr", "grey"),
        ("bl", "black"),
        ("wh", "white"),
        ("wt", "white-transparent"),
    )

    BACKGROUND_COLOR_CHOICES = (
        ("rbl", "delve deeper rainbow  to bottom left"),
        ("rbr", "delve deeper rainbow  to bottom right"),
        ("gd", "golden"),
        ("wh", "white"),
        ("bl","black"),
        ("lb","lightblue"),
        ("pb","pastelblue"),
        ("pp","pastelpurple"),
        ("pr", "purple"),
        ("sg", "seagreen"),
    )

    POST_TYPE_CHOICES = (
        ("tex", "text-based post"),
        ("pic", "picture-based post"),
        ("art", "artwork"),
        
    )
    
    PICTURE_ORIENTATION_CHOICES = (
        ("h", "horizontal"),
        ("v", "vertical"),
    )

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    title =  models.CharField(max_length = 200)
    text = models.TextField()
    brief_description =  models.TextField(blank =  True, null = True)
    authors_comment = models.TextField(blank=True, null=True)
    thumbnail = models.ImageField(blank = True, null = True, upload_to="pictures/")
    created_date = models.DateTimeField(default= timezone.now)
    published_date = models.DateTimeField(blank = True, null = True)

    
    title_align = models.CharField(max_length=1, choices=TITLE_ALIGN_CHOICES, default = "c")
    title_color = models.CharField(max_length=2, choices=TITLE_COLOR_CHOICES, default = "bl")
    title_background = models.CharField(max_length=2, choices=TITLE_BACKGROUND_CHOICES, default = "no")

    show_whole_thumbnail = models.BooleanField(default = False)
    background_color = models.CharField(max_length = 3, choices= BACKGROUND_COLOR_CHOICES, default="rbl")
    show_title_in_header = models.BooleanField(default=True)
    show_title_below_header = models.BooleanField(default = True)

    post_type = models.CharField(max_length=3, choices = POST_TYPE_CHOICES, default="tex")
    picture_orientation = models.CharField(max_length = 1, choices = PICTURE_ORIENTATION_CHOICES, default = "v")

    # add (multiple) tags
    tags= models.ManyToManyField("Tag", related_name = "tags")

    def create_brief_description(self):
        print("calling create_brief_description")
        if not self.brief_description:
            self.brief_description = self.text[:500]
            print("created new description!")
            if len(self.text)<500 and not self.brief_description[-1] in [".", "?", "!"]:
                self.brief_description+=". . ."

    def publish(self):
        self.published_date = timezone.now()
        self.save()
    
    def __str__(self):
        return self.title

    class Meta:
        # default ordering
        ordering=["-published_date"]

"""
class PicturePost(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    title =  models.CharField(max_length = 200)
    text = models.TextField()
    picture = models.ImageField(blank = True, null = True, upload_to="pictures/")
    created_date = models.DateTimeField(default= timezone.now)
    published_date = models.DateTimeField(blank = True, null = True)
"""

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

blog/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Post, Tag, Comment
from django.utils import timezone, safestring
from .forms import PicturePostForm, PostForm, TagForm, CommentForm
#from serializers import PostSerializer, LanguageSerializer
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage

# Create your views here.

def start_page(request):
    featured_post = Post.objects.filter(title__exact = "Epiphany")[0]
    return render(request, "blog/start.html", {"display_logo": True, "featured_post":featured_post})

def post_list(request, isTextPost=1):
    tags = Tag.objects.all().order_by("type", "name")
    if isTextPost:
        posts = Post.objects.filter(published_date__lte = timezone.now(), post_type__exact="tex").order_by("-published_date")
        temp = "blog/post_list.html"
    else:
        posts = Post.objects.filter(published_date__lte = timezone.now()).exclude(post_type__exact = "tex").order_by("-published_date")
        temp = "blog/picture_post_list.html"
    
    return render(request, temp , {"posts": posts, "display_logo": True, "tags": tags, "isTextPost":isTextPost})

def tag_post_list(request, pk, isTextPost):
    current_tag = get_object_or_404(Tag, pk = pk)
    tags = Tag.objects.all().order_by("type", "name")
    if isTextPost==1:
        posts = Post.objects.filter(published_date__lte = timezone.now(), tags__exact=pk, post_type__exact="tex").order_by("-published_date")
    else:
        posts = Post.objects.filter(published_date__lte = timezone.now(), tags__exact=pk).exclude(post_type__exact="tex").order_by("-published_date")
    return render(request, "blog/post_list.html", {"posts": posts, 
                            "display_logo": True, "tags": tags, "current_tag": current_tag,
                            "isTextPost":isTextPost})

"""
def tag_list_post_list(request, pk_list):
    tags=[]
    posts=[]
    for pk in pk_list:
        tags.append(get_object_or_404(Tag, pk = pk))
    posts = Post.objects.filter(published_date__lte = timezone.now(), tags__exact=pk_list).order_by("-published_date")
    return render(request, "blog/post_list.html", {"posts": posts, 
                            "display_logo": True, "tags": tags, "current_tag": current_tag})
"""

def post_detail(request, pk):
    post =  get_object_or_404(Post, pk =pk)
    comments = Comment.objects.filter(post__pk = pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
    if post.post_type == "tex":
        return render(request, "blog/post_detail.html", {"post":post, "isTextPost":1, "comments": comments,'form': form})
    else:
        return render(request, "blog/picture_post_detail.html", {"post":post, "isTextPost":0, "comments": comments,'form': form})

@login_required
def post_new(request, isTextPost = 1):
    if request.method == "POST":
        if isTextPost==0 :
            post_type="picture-based post"
            form = PicturePostForm(request.POST)
        else:
            post_type="text-based post"
            form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit = False)
            post.author = request.user
            #post.published_date = timezone.now()
            post.thumbnail = form.cleaned_data["thumbnail"]
            if isTextPost!=0:
                post.post_type = "tex"
            post.save()
            post.create_brief_description()
            post.tags.set(form.cleaned_data["tags"])
            if "thumbnail" in request.FILES.keys():
                post.thumbnail =  request.FILES["thumbnail"]
            post.save()
            return redirect("post_detail", pk = post.pk)

    else:
        if isTextPost==0:
            post_type="picture-based post"
            form = PicturePostForm()
        else:
            post_type="text-based post"
            form = PostForm()
    return render(request, "blog/post_edit.html", {"form": form,"post_type":post_type})

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    isTextPost = 0
    if post.post_type=="tex":
        isTextPost = 1
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if isTextPost==0:
            form = PicturePostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.tags.set(form.cleaned_data["tags"])
            post.create_brief_description()
            if isTextPost!= 0:
                post.post_type = "tex"
            if "thumbnail" in request.FILES.keys():
                post.thumbnail =  request.FILES["thumbnail"]
            post.save()

            return redirect('post_detail', pk=post.pk) #render(request, "blog/post_edit.html",{"form":form, "thumbnail" : post.thumbnail})#

    else:
        form = PostForm(instance=post)
        if not isTextPost:
            form = PicturePostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form, "current_post": post})

@login_required
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    isTextPost = post.post_type == "tex"
    post.delete()
    return redirect("post_list", isTextPost=isTextPost)

@login_required
def tag_new(request):
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            tag = form.save(commit = False)
            tag.save()
            return redirect("post_list", isTextPost = 1)
    else:
        form = TagForm()
    return render(request, "blog/tag_edit.html", {"form": form})


a_tag = Tag.objects.filter(name__exact="Fantasy")

@login_required
def tag_edit(request, pk):
    tag = get_object_or_404(Tag, pk=pk)
    if request.method == "POST":
        form = TagForm(request.POST, instance=tag)
        if form.is_valid():
            tag = form.save(commit = False)
            tag.save()
            return render(request, "blog/tag_edit.html", {"form": form, "current_tag":tag})#redirect("post_list", isTextPost = 1) #redirect("tag_post_list", pk=tag.pk, isTextPost=1)
    else:
        form = TagForm(instance=tag)
    return render(request, "blog/tag_edit.html", {"form": form, "current_tag":tag})

@login_required
def tag_delete(request, pk):
    tag = get_object_or_404(Tag, pk=pk)
    tag.delete()
    return redirect("post_list", isTextPost=1)

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
    
        <!-- <script type="text/javascript" src="/Blog/code.js"></script> -->
        <script type="text/javascript" src="{% static '/js/accordion_code.js' %}"></script>
        {% if display_logo %}
        <script type="text/javascript" src="{% static '/js/logo_code.js' %}"></script>
        {% endif %}
        <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
        <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script> -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
        <title>Delve Deeper</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Cherry Swash|Sofia|Rubik Moonrocks|Amatic SC|Stick No Bills|Orbitron|Special Elite|Blaka|Marck Script|Audiowide|Splash|Ubuntu">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        
        <link rel="stylesheet" href="{% static '/css/blog.css'%}">
        <!-- <link rel="stylesheet" href="/static/css/blog.css"> -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    
    <body>
        {% if display_logo %}
        <div id="canvasBox" class="container-fluid" onclick="location.href='/start';">
        </div>

        {% endif %}
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark navbar-fixed-top" style="margin:0px; top:0px;"> <!-- top: 7px;-->
            <div class="container-fluid">
            <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'start_page' %}"
                        style="font-family:'Rubik Moonrocks'; font-size:20px; margin-left:10px;">Delve Deeper</a>
                </div>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" id="stories_link" href="{% url 'post_list' isTextPost=1 %}">Words</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="code_link" href="#">Code</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="art_link" href="{% url 'post_list' isTextPost=0 %}">Art</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="gallery_link" href="#">Gallery</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="about_link" href="#">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" id="disabled_link"> </a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a class="nav-link disabled" href="#"><i class="fa fa-user-circle-o"></i> {{ user.username }} </a> 
                    </li>
                    <li class="nav-item">
                       <a  class="nav-link fa fa-sign-out icon-nav-bar" href="{% url 'logout' %}"></a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link fa fa-sign-in icon-nav-bar" href="{% url 'login' %}" class="top-menu"></a>
                    </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li class="nav-item"><a  class="nav-link fa fa-file-text-o icon-nav-bar"  href="{% url 'post_new' isTextPost=1 %}" class="top-menu">   
                       <!-- {% include "./icons/file-earmark-plus.svg" %}--> </a> </li>
                    <li class="nav-item"><a class="nav-link fa fa-file-picture-o icon-nav-bar"  href="{% url 'post_new' isTextPost=0 %}">
                    </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        {% block content %}
        {% endblock %}

    </body>

blog/templates/blog/base_deprecated.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <!-- <script type="text/javascript" src="/Blog/code.js"></script> -->
        <script type="text/javascript" src="{% static 'js/logo_code.js'%}"></script>
        <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script> -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <title>Delve Deeper</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Sofia|Rubik Moonrocks|Amatic SC|Stick No Bills|Orbitron|Special Elite|Blaka|Marck Script|Audiowide|Splash|Ubuntu">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/blog.css'%}">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    
    <body>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark navbar-fixed-top" style="margin:0px; top:-7px;">
            <div class="container-fluid">
            <div class="navbar-header">
                    <a class="navbar-brand" href="/Blog/"
                        style="font-family:'Rubik Moonrocks'; font-size:20px; margin-left:10px;">Delve Deeper</a>
                </div>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" id="stories_link" href="/Blog/Stories/">Words</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="code_link" href="/simple Fractal Tree/">Code</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="art_link" href="#">Art</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="gallery_link" href="/Blog/Gallery/">Gallery</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="about_link" href="/Blog/about.php">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" id="disabled_link"> </a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a class="nav-link disabled" href="#">{{ user.username }} </a> 
                    </li>
                    <li class="nav-item">
                       <a  class="nav-link" href="{% url 'logout' %}">Log out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}" class="top-menu">Login</a>
                    </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li><a style="color:white;" href="{% url 'post_new' %}" class="top-menu">
                        {% include "./icons/file-earmark-plus.svg" %}
                    </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        {% block content %}
        {% endblock %}

    </body>
    <!-- <head>
        <title>Django Girls blog</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/blog.css'%}">
    </head>
    <body>
        <header class="page-header">
          <div class="container">
            

            {% if user.is_authenticated %}
                <a href="{% url 'post_new' %}" class="top-menu">
                    {% include "./icons/file-earmark-plus.svg" %}
                </a>
                <p class="top-menu">Hello {{ user.username }} 
                    <small>(<a href="{% url 'logout' %}">Log out</a>)</small>
                </p>
            {% else %}
                <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
            {% endif %}
            <h1><a href="/">Django Girls Blog</a></h1>
          </div>
        </header>
        <main class="container">
            <div class="row">
                <div class="col">
                    content stuff
                </div>
            </div>
        </main> 
    </body> -->
</html>

blog/templates/blog/picture_post_detail.html
{% extends 'blog/base.html' %}

{% block content %}

{% if post.picture_orientation == "v" %}

<img class="picture-post-header-box mx-auto d-block picture-vertical gold-frame" src="{{ post.thumbnail.url}}"></img>
{% else %}
<img class="picture-post-header-box mx-auto d-block picture-horizontal gold-frame" src="{{ post.thumbnail.url}}"></img>
{% endif %}

<div class="container-fluid article-container">
        
    <article class="post">

        <aside class="actions">
            {% if user.is_authenticated %}
                <a class="btn btn-secondary" href="{% url 'post_edit' pk=post.pk %}">
                    {% include './icons/pencil-fill.svg' %}
                </a>
            {% endif %}
        </aside>

        {% if post.published_date %}
            <time class="date">
                <i class="fa fa-calendar"></i> {{ post.published_date }}
            </time>
        {% endif %}
        {% if False %}
        <div class="tag-box">
            {% for tag in post.tags.all %}
            <a href="{% url 'tag_post_list' pk=tag.pk %}" class="badge badge-pill badge-tag {{tag.style}}">{{ tag.name }}</a>
            {% endfor %}
        </div>
        {% endif %}
        <h2>{{ post.title }}</h2>
        {% if "<p>" in post.text or "<br>" in post.text %}
            <p>{{ post.text}}</p>
        {% else %}
            <p>{{ post.text|linebreaksbr }}</p>
        {% endif %}

        
        {% if post.authors_comment %}
        <br>
        <button class="accordion">Author's Comment</button>
        <div class="panel">
            <p>{{ post.authors_comment|linebreaksbr }}</p>
        </div>
        {% endif %}
    </article>
    
</div>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
{% autoescape off %}

{% if post.thumbnail %}
{% if post.show_whole_thumbnail %}
        <div class="container-fluid text-center post-header-box background-color-{{post.background_color}} show-complete-image" style="background-image: url('{{ post.thumbnail.url}}');" >
    {% else %}
        <div class="container-fluid text-center post-header-box background-color-{{post.background_color}}" style="background-image: url('{{ post.thumbnail.url}}');" >
    {% endif %}
{% else %}
    <div class="container-fluid text-center post-header-box background-color-{{post.background_color}}" >
{% endif %}
{% if post.show_title_in_header %}
    <table style="height: 100%; width: 100%;">
        <td class= "{{post.get_title_align_display}}">
            <div class = "title-background-{{post.get_title_background_display}}" style ="color:var(--{{post.get_title_color_display}})">{{ post.title }}</div>
        </td>
    </table>
    {% endif %}
</div>
    <div class="container-fluid article-container">
        
        <article class="post">

            <aside class="actions">
                {% if user.is_authenticated %}
                    <a class="btn btn-secondary" href="{% url 'post_edit' pk=post.pk %}">
                        {% include './icons/pencil-fill.svg' %}
                    </a>
                {% endif %}
            </aside>

            {% if post.published_date %}
                <time class="date">
                    <i class="fa fa-calendar"></i> {{ post.published_date }}
                </time>
            {% endif %}
            <div class="tag-box">
                {% for tag in post.tags.all %}
                <a href="{% url 'tag_post_list' pk=tag.pk isTextPost=isTextPost %}" class="badge badge-pill badge-tag {{tag.style}}">{{ tag.name }}</a>
                {% endfor %}
            </div>
            {% if post.show_title_below_header %}
            <h2>{{ post.title }}</h2>
            {% else %}
            <br>
            {% endif %}
            <br>

            {% if False %}
            <img src="{{ post.thumbnail.url}}" alt="connect" style="max-height:300px">
            {% endif %}
             
            {% if "<p>" in post.text or "<br>" in post.text %}
                <p>{{ post.text}}</p>
            {% else %}
                <p>{{ post.text|linebreaksbr }}</p>
            {% endif %}

            
            {% if post.authors_comment %}
            <br>
            <button class="accordion">Author's Comment</button>
            <div class="panel">
                <p>{{ post.authors_comment|linebreaksbr }}</p>
            </div>
            {% endif %}
        </article>
        {% endautoescape %}
    
        <hr>
        <h3>Comments ({{ post.comments.count }})</h3>

        {% if comments %}
            {% for comment in comments %}
            <div class="comment">
                <div class="date">{{ comment.created_date }}</div>
                <i class="fa fa-user-circle-o"></i> <strong>{{ comment.author }}</strong>
                <p>{{ comment.text|linebreaks }}</p>
            </div>

            {% endfor %}
        {% else %}
            <p>No comments here yet.</p>
        {% endif %}

        <h3>New comment</h3>
        <div class="container-fluid form comment">
            <form method="POST" class="post-form" style="width:100%; padding-left:10px; padding-right:10px;"> {%csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="save btn btn-secondary">Submit</button>
                Note: The owner of this blog will delete inappropriate comments.
            </form>
        </div>
        
    </div>
{% endblock %}